### ISSUE TITLE
The content of activation is reverse

### ISSUE THREAD

**Issue by namikimeiko** [Bisonai/mobilenetv3-tensorflow#11]
In layers.py line 41~56:

HardSigmoid() contains h-swish,  and HardSwish() contains h-sigmoid.
Maybe simple mistake.

Regards.

**Comment by martinkersner** [comment]
Hi @namikimeiko The difference between `HardSigmoid` and `HardSwish` is just minor. `HardSwish` just additionally multiplies with its input, therefore you maybe got confused. 

<img src="https://i.imgur.com/3oILxtB.png" />

Cheers,
Martin

**Comment by namikimeiko** [comment]
Oh, I understand.
I'm very sorry, I mistook, you are true.

Thank you for your response.
