### ISSUE TITLE
Number of filters in comparison to official Keras implementation

### ISSUE THREAD

**Issue by rafael-wampfler** [Bisonai/mobilenetv3-tensorflow#18]
Hello

As far as I can see the large model conatins filters of size 16, 24, 24, 40, 40, 40, 80, 80, 80, 80, 112, 112, 160, 160, 160. On the other hand, the official Keras [MobileNetV2 ](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/applications/mobilenet_v2.py#L301-L312) implementation contains filters of size 16, 24, 24, 32, 32, 32, 64, 64, 64, 64, 96, 96, 96, 160, 160, 160, 320.

Why does this implementation here differ in terms of the number of filters?

**Comment by martinkersner** [comment]
Hi @Eichhof,

Our implementation is based on [MobileNetV3](https://arxiv.org/abs/1905.02244) paper. MobileNetV3 architecture is different from MobileNetV2.

Cheers,
Martin
