### ISSUE TITLE
Implementing Semantic Segmentation Head?

### ISSUE THREAD

**Issue by fzyzcjy** [Bisonai/mobilenetv3-tensorflow#3]
Firstly, thanks for the implementation of the MobileNetV3!

Do you have an interest in implementing the semantic segmentation head described in section 6.4? I am currently planning to implement that, so if you have an interest, we can work together to do it!

**Comment by martinkersner** [comment]
Hello @fzyzcjy!

Thank you for your interest in our implementation. Currently, we are not planning to implement segmentation head.

Cheers,
Martin

**Comment by fzyzcjy** [comment]
OK fine!
