### ISSUE TITLE
Do you know how to use NAS and NetAdapt to optimize mobilenet block and layer to adapt to other task?

### ISSUE THREAD

**Issue by alexliyang** [Bisonai/mobilenetv3-tensorflow#6]
when I use paper parameters to train my task , the result is not good enough.

how to use NAS and NetAdapt to optimize mobilenet block and layer to adapt to other task?

**Comment by martinkersner** [comment]
Hi @alexliyang!

MobileNetV3 and its predecessors should be suitable for many different tasks. What task are you training for?

Cheers,
Martin

**Comment by alexliyang** [comment]
Hi, @martinkersner   :+1: 
    I use MobilenetV3 to train image classes for mobilephone, but on my dataset, the result is not good , so I  try to optimize the parameters again.
    Maybe it is a big task

**Comment by martinkersner** [comment]
@alexliyang What does your data look like? How many classes do you train for? The problem could be due to the hyperparameters you use. It is better to investigate it before moving on NAS or NetAdapt.

**Comment by alexliyang** [comment]
@martinkersner  my data just like flowers, pets, foods and others' image , about 7 classes, I resized the images to 224,224 or 128,128 ,  I trained mobilenetv3 on the dataset about 100 epoches, the acc is about 0.95, but on the test data  is very poor

**Comment by martinkersner** [comment]
@alexliyang Is your test data from the same distribution as train data? Do you use any preprocessing/augmentation? Did you try to train with CIFAR10 or MNIST before?
