### ISSUE TITLE
problem in build_mobilenetv3   NotImplementedError:

### ISSUE THREAD

**Issue by william0418** [Bisonai/mobilenetv3-tensorflow#7]
Python 3.6.7
tensorflow-gpu       1.12.0

![擷取](https://user-images.githubusercontent.com/42887704/58540409-e5ac7500-822b-11e9-9352-d1f6276116f9.PNG)
![擷取1](https://user-images.githubusercontent.com/42887704/58540420-ea712900-822b-11e9-9313-e8f14baabd34.PNG)

**Comment by martinkersner** [comment]
Hi @william0418,

Thank you for your error report! We do not encounter such an exception when we use `tensorflow-gpu==1.13.1`. Could you try that version?

Cheers,
Martin

**Comment by martinkersner** [comment]
@william0418 You can see that there is no problem with creating a network. Here is an example in Google Colab https://colab.research.google.com/drive/1DCA6xMsl82mvGNTACF5NP7xduSeWJnwb
